# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(528, 752)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.friendListView = QtWidgets.QListView(self.centralwidget)
        self.friendListView.setGeometry(QtCore.QRect(10, 40, 501, 631))
        self.friendListView.setObjectName("friendListView")
        self.friendsOnlineLabel = QtWidgets.QLabel(self.centralwidget)
        self.friendsOnlineLabel.setGeometry(QtCore.QRect(10, 0, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.friendsOnlineLabel.setFont(font)
        self.friendsOnlineLabel.setObjectName("friendsOnlineLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 670, 501, 31))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 528, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuChat = QtWidgets.QMenu(self.menubar)
        self.menuChat.setObjectName("menuChat")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuNotification = QtWidgets.QMenu(self.menubar)
        self.menuNotification.setObjectName("menuNotification")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Account = QtWidgets.QAction(MainWindow)
        self.actionNew_Account.setObjectName("actionNew_Account")
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionNew_Friend = QtWidgets.QAction(MainWindow)
        self.actionNew_Friend.setObjectName("actionNew_Friend")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFriends = QtWidgets.QAction(MainWindow)
        self.actionFriends.setObjectName("actionFriends")
        self.actionNew_Group_Chat = QtWidgets.QAction(MainWindow)
        self.actionNew_Group_Chat.setObjectName("actionNew_Group_Chat")
        self.actionFriend_Request = QtWidgets.QAction(MainWindow)
        self.actionFriend_Request.setObjectName("actionFriend_Request")
        self.actionUnread_Messages = QtWidgets.QAction(MainWindow)
        self.actionUnread_Messages.setObjectName("actionUnread_Messages")
        self.menuFile.addAction(self.actionSettings)
        self.menuChat.addAction(self.actionNew_Group_Chat)
        self.menuChat.addSeparator()
        self.menuChat.addAction(self.actionFriends)
        self.menuChat.addAction(self.actionNew_Friend)
        self.menuChat.addSeparator()
        self.menuChat.addAction(self.actionLogin)
        self.menuHelp.addAction(self.actionAbout)
        self.menuNotification.addAction(self.actionFriend_Request)
        self.menuNotification.addAction(self.actionUnread_Messages)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuChat.menuAction())
        self.menubar.addAction(self.menuNotification.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FiboChat"))
        self.friendsOnlineLabel.setText(_translate("MainWindow", "Friends online:"))
        self.label.setText(_translate("MainWindow", "You have 0 notifications"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuChat.setTitle(_translate("MainWindow", "Chat"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuNotification.setTitle(_translate("MainWindow", "Notification"))
        self.actionNew_Account.setText(_translate("MainWindow", "New Account"))
        self.actionLogin.setText(_translate("MainWindow", "Login/Register"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionNew_Friend.setText(_translate("MainWindow", "Add Friend"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionFriends.setText(_translate("MainWindow", "Friends"))
        self.actionNew_Group_Chat.setText(_translate("MainWindow", "New Group Chat"))
        self.actionFriend_Request.setText(_translate("MainWindow", "Friend Request"))
        self.actionUnread_Messages.setText(_translate("MainWindow", "Unread Messages"))

