# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisterDialogGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(367, 355)
        self.label = QtWidgets.QLabel(Register)
        self.label.setGeometry(QtCore.QRect(0, 0, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.registerButton = QtWidgets.QPushButton(Register)
        self.registerButton.setGeometry(QtCore.QRect(220, 300, 101, 40))
        self.registerButton.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.registerButton.setFont(font)
        self.registerButton.setObjectName("registerButton")
        self.resetButton = QtWidgets.QPushButton(Register)
        self.resetButton.setGeometry(QtCore.QRect(40, 300, 111, 40))
        self.resetButton.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resetButton.setFont(font)
        self.resetButton.setObjectName("resetButton")
        self.formLayoutWidget = QtWidgets.QWidget(Register)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 40, 361, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(96, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.firstNameEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.firstNameEdit.setFont(font)
        self.firstNameEdit.setText("")
        self.firstNameEdit.setObjectName("firstNameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.firstNameEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lastNameEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lastNameEdit.setFont(font)
        self.lastNameEdit.setText("")
        self.lastNameEdit.setObjectName("lastNameEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lastNameEdit)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.emailEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.emailEdit.setFont(font)
        self.emailEdit.setText("")
        self.emailEdit.setObjectName("emailEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.emailEdit)
        self.line = QtWidgets.QFrame(Register)
        self.line.setGeometry(QtCore.QRect(10, 160, 331, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayoutWidget_2 = QtWidgets.QWidget(Register)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 170, 361, 130))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.usernameEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.usernameEdit.setFont(font)
        self.usernameEdit.setText("")
        self.usernameEdit.setObjectName("usernameEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameEdit)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.passwordEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setText("")
        self.passwordEdit.setObjectName("passwordEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordEdit)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.confPassEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.confPassEdit.setFont(font)
        self.confPassEdit.setText("")
        self.confPassEdit.setObjectName("confPassEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.confPassEdit)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Dialog"))
        self.label.setText(_translate("Register", "Register"))
        self.registerButton.setText(_translate("Register", "Register"))
        self.resetButton.setText(_translate("Register", "Reset"))
        self.label_4.setText(_translate("Register", "First Name"))
        self.label_2.setText(_translate("Register", "Last Name"))
        self.label_6.setText(_translate("Register", "Email"))
        self.label_5.setText(_translate("Register", "Username"))
        self.label_3.setText(_translate("Register", "Password"))
        self.label_7.setText(_translate("Register", "Confirm Pass"))

